### ISSUE TITLE
DOCs: Example on using baby parse with a local file 

### ISSUE THREAD

**Issue by 0o-de-lally** [modweb/meteor-baby-parse#1]
Hi there, Thanks for providing and maintaining this package.  Could you please provide a 'quickstart' example with a local file? I'm trying to go by the papa parse docs and can't seem to get started.

This example, trying to read a file directly:
    console.log(Baby.parseFiles('test.csv'));

Produces this error :

```
TypeError: Object #<Object> has no method 'parseFiles'
```

This example, trying to read a file directly:
    console.log(Baby.parse('test.csv'));

Produces a list of 1 string with the filename:

```
[ [ 'test.csv' ] ]
```

This example, reading from node fs first:

```
var fs = Npm.require('fs');
var myFile = fs.readFileSync('../../../../../test.csv');

parsed = Baby.parse(myFile);
console.log(parsed.data);
```

Produces an error: 

```
TypeError: Object x,x,x has no method 'substr'
```

**Comment by jfols** [comment]
Are you running that code on the server or the client?

**Comment by 0o-de-lally** [comment]
Running in the server. Do you have an example I can follow?

**Comment by jfols** [comment]
Try to read the file directly like this:

``` js
filePath = process.env.PWD + "/test.csv";
parsed = Baby.parseFiles(filePath);
```

Can you provide the full output for the error `TypeError: Object x,x,x has no method 'substr'`?

**Comment by 0o-de-lally** [comment]
If I pass the full path as you suggest it will work.
I have the a file, public/data/test.csv

However if I pass
parsed = Baby.parseFiles('public/data/test.csv');

I20150817-17:54:42.877(-4)?   errors:

I20150817-17:54:42.877(-4)?    [ { [Error: ENOENT, no such file or
directory 'public/data/test.csv']

I20150817-17:54:42.877(-4)?        errno: 34,

I20150817-17:54:42.877(-4)?        code: 'ENOENT',

I20150817-17:54:42.877(-4)?        path: 'public/data/test.csv',

I20150817-17:54:42.877(-4)?        syscall: 'open' } ] }

Same error for:

parsed = Baby.parseFiles('data/test.csv');

I20150817-17:54:24.550(-4)? { data: [],

I20150817-17:54:24.551(-4)?   errors:

I20150817-17:54:24.551(-4)?    [ { [Error: ENOENT, no such file or
directory 'data/test.csv']

I20150817-17:54:24.551(-4)?        errno: 34,

I20150817-17:54:24.551(-4)?        code: 'ENOENT',

I20150817-17:54:24.552(-4)?        path: 'data/test.csv',

I20150817-17:54:24.552(-4)?        syscall: 'open' } ] }

**Comment by jfols** [comment]
Glad to hear it worked!

`public/data/test.csv` isn't a valid path, so that error is to be expected. You could write a wrapper around `Baby.parseFiles` that accepts a relative path. 

I will add a note in the documentation to prepend the process env path to any relative paths.

**Comment by keyscores** [comment]
Unrelated question, is there an undocumented option for the output to be JSON and not arrays?
